/**
 * AlertingEventTypeEvent.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.zeus.soap.zxtm._1_0;

public class AlertingEventTypeEvent implements java.io.Serializable {
    private java.lang.String _value_;
    private static java.util.HashMap _table_ = new java.util.HashMap();

    // Constructor
    protected AlertingEventTypeEvent(java.lang.String value) {
        _value_ = value;
        _table_.put(_value_,this);
    }

    public static final java.lang.String _value1 = "ALL";
    public static final java.lang.String _value2 = "cloudcredentials_ALL";
    public static final java.lang.String _value3 = "cloudcredentials_apistatusprocesshanging";
    public static final java.lang.String _value4 = "cloudcredentials_autoscaleresponseparseerror";
    public static final java.lang.String _value5 = "cloudcredentials_autoscalestatusupdateerror";
    public static final java.lang.String _value6 = "cloudcredentials_autoscalingprocesstimedout";
    public static final java.lang.String _value7 = "cloudcredentials_usedcredsdeleted";
    public static final java.lang.String _value8 = "config_ALL";
    public static final java.lang.String _value9 = "config_confadd";
    public static final java.lang.String _value10 = "config_confdel";
    public static final java.lang.String _value11 = "config_confmod";
    public static final java.lang.String _value12 = "config_confok";
    public static final java.lang.String _value13 = "faulttolerance_ALL";
    public static final java.lang.String _value14 = "faulttolerance_activatealldead";
    public static final java.lang.String _value15 = "faulttolerance_activatedautomatically";
    public static final java.lang.String _value16 = "faulttolerance_allmachinesok";
    public static final java.lang.String _value17 = "faulttolerance_dropec2ipwarn";
    public static final java.lang.String _value18 = "faulttolerance_dropipinfo";
    public static final java.lang.String _value19 = "faulttolerance_dropipwarn";
    public static final java.lang.String _value20 = "faulttolerance_ec2flipperraiselocalworking";
    public static final java.lang.String _value21 = "faulttolerance_ec2flipperraiseothersdead";
    public static final java.lang.String _value22 = "faulttolerance_ec2iperr";
    public static final java.lang.String _value23 = "faulttolerance_ec2nopublicip";
    public static final java.lang.String _value24 = "faulttolerance_ec2nosecondaryprivateip";
    public static final java.lang.String _value25 = "faulttolerance_ec2vpceipassocerr";
    public static final java.lang.String _value26 = "faulttolerance_ec2vpciderr";
    public static final java.lang.String _value27 = "faulttolerance_flipperbackendsworking";
    public static final java.lang.String _value28 = "faulttolerance_flipperdadreraise";
    public static final java.lang.String _value29 = "faulttolerance_flipperfrontendsworking";
    public static final java.lang.String _value30 = "faulttolerance_flipperipexists";
    public static final java.lang.String _value31 = "faulttolerance_flipperraiselocalworking";
    public static final java.lang.String _value32 = "faulttolerance_flipperraiseosdrop";
    public static final java.lang.String _value33 = "faulttolerance_flipperraiseothersdead";
    public static final java.lang.String _value34 = "faulttolerance_flipperraiseremotedropped";
    public static final java.lang.String _value35 = "faulttolerance_flipperrecovered";
    public static final java.lang.String _value36 = "faulttolerance_machinefail";
    public static final java.lang.String _value37 = "faulttolerance_machineok";
    public static final java.lang.String _value38 = "faulttolerance_machinerecovered";
    public static final java.lang.String _value39 = "faulttolerance_machinetimeout";
    public static final java.lang.String _value40 = "faulttolerance_multihostload";
    public static final java.lang.String _value41 = "faulttolerance_pingbackendfail";
    public static final java.lang.String _value42 = "faulttolerance_pingfrontendfail";
    public static final java.lang.String _value43 = "faulttolerance_pinggwfail";
    public static final java.lang.String _value44 = "faulttolerance_statebaddata";
    public static final java.lang.String _value45 = "faulttolerance_stateconnfail";
    public static final java.lang.String _value46 = "faulttolerance_stateok";
    public static final java.lang.String _value47 = "faulttolerance_statereadfail";
    public static final java.lang.String _value48 = "faulttolerance_statetimeout";
    public static final java.lang.String _value49 = "faulttolerance_stateunexpected";
    public static final java.lang.String _value50 = "faulttolerance_statewritefail";
    public static final java.lang.String _value51 = "faulttolerance_zclustermoderr";
    public static final java.lang.String _value52 = "general_ALL";
    public static final java.lang.String _value53 = "general_aptimizerresourcetoolargeforcache";
    public static final java.lang.String _value54 = "general_autherror";
    public static final java.lang.String _value55 = "general_autoscalinglicenseerror";
    public static final java.lang.String _value56 = "general_confrepfailed";
    public static final java.lang.String _value57 = "general_confreptimeout";
    public static final java.lang.String _value58 = "general_fewfreefds";
    public static final java.lang.String _value59 = "general_geodataloadfail";
    public static final java.lang.String _value60 = "general_hardware";
    public static final java.lang.String _value61 = "general_licensetoomanylocations";
    public static final java.lang.String _value62 = "general_logdiskfull";
    public static final java.lang.String _value63 = "general_logdiskoverload";
    public static final java.lang.String _value64 = "general_numlocations-exceeded";
    public static final java.lang.String _value65 = "general_numnodes-exceeded";
    public static final java.lang.String _value66 = "general_numpools-exceeded";
    public static final java.lang.String _value67 = "general_numtipg-exceeded";
    public static final java.lang.String _value68 = "general_restartrequired";
    public static final java.lang.String _value69 = "general_running";
    public static final java.lang.String _value70 = "general_sslcrltoobig";
    public static final java.lang.String _value71 = "general_timemovedback";
    public static final java.lang.String _value72 = "general_zxtmhighload";
    public static final java.lang.String _value73 = "general_zxtmswerror";
    public static final java.lang.String _value74 = "java_ALL";
    public static final java.lang.String _value75 = "java_javadied";
    public static final java.lang.String _value76 = "java_javanotfound";
    public static final java.lang.String _value77 = "java_javastarted";
    public static final java.lang.String _value78 = "java_javastartfail";
    public static final java.lang.String _value79 = "java_javastop";
    public static final java.lang.String _value80 = "java_javaterminatefail";
    public static final java.lang.String _value81 = "java_servleterror";
    public static final java.lang.String _value82 = "licensekeys_ALL";
    public static final java.lang.String _value83 = "licensekeys_analyticslicensedisabled";
    public static final java.lang.String _value84 = "licensekeys_analyticslicenseenabled";
    public static final java.lang.String _value85 = "licensekeys_autoscalinglicensedisabled";
    public static final java.lang.String _value86 = "licensekeys_autoscalinglicenseenabled";
    public static final java.lang.String _value87 = "licensekeys_bwlimited";
    public static final java.lang.String _value88 = "licensekeys_cachesizereduced";
    public static final java.lang.String _value89 = "licensekeys_expired";
    public static final java.lang.String _value90 = "licensekeys_expiresoon";
    public static final java.lang.String _value91 = "licensekeys_lessmemallowed";
    public static final java.lang.String _value92 = "licensekeys_license-authorized";
    public static final java.lang.String _value93 = "licensekeys_license-authorized-ts";
    public static final java.lang.String _value94 = "licensekeys_license-graceperiodexpired";
    public static final java.lang.String _value95 = "licensekeys_license-graceperiodexpired-ts";
    public static final java.lang.String _value96 = "licensekeys_license-rejected-authorized";
    public static final java.lang.String _value97 = "licensekeys_license-rejected-authorized-ts";
    public static final java.lang.String _value98 = "licensekeys_license-rejected-unauthorized";
    public static final java.lang.String _value99 = "licensekeys_license-rejected-unauthorized-ts";
    public static final java.lang.String _value100 = "licensekeys_license-timedout-authorized";
    public static final java.lang.String _value101 = "licensekeys_license-timedout-authorized-ts";
    public static final java.lang.String _value102 = "licensekeys_license-timedout-unauthorized";
    public static final java.lang.String _value103 = "licensekeys_license-timedout-unauthorized-ts";
    public static final java.lang.String _value104 = "licensekeys_license-unauthorized";
    public static final java.lang.String _value105 = "licensekeys_licenseclustertoobig";
    public static final java.lang.String _value106 = "licensekeys_licensecorrupt";
    public static final java.lang.String _value107 = "licensekeys_morememallowed";
    public static final java.lang.String _value108 = "licensekeys_ssltpslimited";
    public static final java.lang.String _value109 = "licensekeys_tpslimited";
    public static final java.lang.String _value110 = "licensekeys_unlicensed";
    public static final java.lang.String _value111 = "licensekeys_usingdevlicense";
    public static final java.lang.String _value112 = "licensekeys_usinglicense";
    public static final java.lang.String _value113 = "locations_ALL";
    public static final java.lang.String _value114 = "locations_locationfail";
    public static final java.lang.String _value115 = "locations_locationmonitorfail";
    public static final java.lang.String _value116 = "locations_locationmonitorok";
    public static final java.lang.String _value117 = "locations_locationok";
    public static final java.lang.String _value118 = "locations_locationsoapfail";
    public static final java.lang.String _value119 = "locations_locationsoapok";
    public static final java.lang.String _value120 = "locations_locempty";
    public static final java.lang.String _value121 = "locations_locmovemachine";
    public static final java.lang.String _value122 = "monitors_ALL";
    public static final java.lang.String _value123 = "monitors_monitorfail";
    public static final java.lang.String _value124 = "monitors_monitorok";
    public static final java.lang.String _value125 = "pools_ALL";
    public static final java.lang.String _value126 = "pools_apichangeprocesshanging";
    public static final java.lang.String _value127 = "pools_autonodecreationcomplete";
    public static final java.lang.String _value128 = "pools_autonodecreationstarted";
    public static final java.lang.String _value129 = "pools_autonodedestroyed";
    public static final java.lang.String _value130 = "pools_autonodedestructioncomplete";
    public static final java.lang.String _value131 = "pools_autonodedisappeared";
    public static final java.lang.String _value132 = "pools_autonodeexisted";
    public static final java.lang.String _value133 = "pools_autonodestatuschange";
    public static final java.lang.String _value134 = "pools_autoscalednodecontested";
    public static final java.lang.String _value135 = "pools_autoscaledpoolrefractory";
    public static final java.lang.String _value136 = "pools_autoscaledpooltoobig";
    public static final java.lang.String _value137 = "pools_autoscaledpooltoosmall";
    public static final java.lang.String _value138 = "pools_autoscaleinvalidargforcreatenode";
    public static final java.lang.String _value139 = "pools_autoscaleinvalidargfordeletenode";
    public static final java.lang.String _value140 = "pools_autoscalepoolconfupdate";
    public static final java.lang.String _value141 = "pools_autoscalewrongimageid";
    public static final java.lang.String _value142 = "pools_autoscalewrongname";
    public static final java.lang.String _value143 = "pools_autoscalewrongsizeid";
    public static final java.lang.String _value144 = "pools_autoscalingchangeprocessfailure";
    public static final java.lang.String _value145 = "pools_autoscalingdisabled";
    public static final java.lang.String _value146 = "pools_autoscalinghitfloor";
    public static final java.lang.String _value147 = "pools_autoscalinghitroof";
    public static final java.lang.String _value148 = "pools_autoscalinghysteresiscantgrow";
    public static final java.lang.String _value149 = "pools_autoscalinghysteresiscantshrink";
    public static final java.lang.String _value150 = "pools_autoscalingpoolstatechange";
    public static final java.lang.String _value151 = "pools_autoscalingresuscitatepool";
    public static final java.lang.String _value152 = "pools_badcontentlen";
    public static final java.lang.String _value153 = "pools_cannotshrinkemptypool";
    public static final java.lang.String _value154 = "pools_ehloinvalid";
    public static final java.lang.String _value155 = "pools_nodefail";
    public static final java.lang.String _value156 = "pools_noderesolvefailure";
    public static final java.lang.String _value157 = "pools_noderesolvemultiple";
    public static final java.lang.String _value158 = "pools_nodeworking";
    public static final java.lang.String _value159 = "pools_nostarttls";
    public static final java.lang.String _value160 = "pools_pooldied";
    public static final java.lang.String _value161 = "pools_poolnonodes";
    public static final java.lang.String _value162 = "pools_poolok";
    public static final java.lang.String _value163 = "pools_starttlsinvalid";
    public static final java.lang.String _value164 = "protection_ALL";
    public static final java.lang.String _value165 = "protection_triggersummary";
    public static final java.lang.String _value166 = "rules_ALL";
    public static final java.lang.String _value167 = "rules_aptimizedisabled";
    public static final java.lang.String _value168 = "rules_aptimizeuseunknownprofile";
    public static final java.lang.String _value169 = "rules_aptimizeuseunknownscope";
    public static final java.lang.String _value170 = "rules_datastorefull";
    public static final java.lang.String _value171 = "rules_forwardproxybadhost";
    public static final java.lang.String _value172 = "rules_invalidemit";
    public static final java.lang.String _value173 = "rules_norate";
    public static final java.lang.String _value174 = "rules_poolactivenodesunknown";
    public static final java.lang.String _value175 = "rules_pooluseunknown";
    public static final java.lang.String _value176 = "rules_ruleabort";
    public static final java.lang.String _value177 = "rules_rulebodycomperror";
    public static final java.lang.String _value178 = "rules_rulebufferlarge";
    public static final java.lang.String _value179 = "rules_rulelogmsginfo";
    public static final java.lang.String _value180 = "rules_rulelogmsgserious";
    public static final java.lang.String _value181 = "rules_rulelogmsgwarn";
    public static final java.lang.String _value182 = "rules_rulenopersistence";
    public static final java.lang.String _value183 = "rules_rulesinvalidrequestbody";
    public static final java.lang.String _value184 = "rules_rulestreamerrorgetresponse";
    public static final java.lang.String _value185 = "rules_rulestreamerrorinternal";
    public static final java.lang.String _value186 = "rules_rulestreamerrornotenough";
    public static final java.lang.String _value187 = "rules_rulestreamerrornotfinished";
    public static final java.lang.String _value188 = "rules_rulestreamerrornotstarted";
    public static final java.lang.String _value189 = "rules_rulestreamerrorprocessfailure";
    public static final java.lang.String _value190 = "rules_rulestreamerrortoomuch";
    public static final java.lang.String _value191 = "rules_rulexmlerr";
    public static final java.lang.String _value192 = "rules_serviceruleabort";
    public static final java.lang.String _value193 = "rules_servicerulelocdead";
    public static final java.lang.String _value194 = "rules_servicerulelocnotconfigured";
    public static final java.lang.String _value195 = "rules_servicerulelocunknown";
    public static final java.lang.String _value196 = "services_ALL";
    public static final java.lang.String _value197 = "services_glbdeadlocmissingips";
    public static final java.lang.String _value198 = "services_glbfailalter";
    public static final java.lang.String _value199 = "services_glblogwritefail";
    public static final java.lang.String _value200 = "services_glbmissingips";
    public static final java.lang.String _value201 = "services_glbnewmaster";
    public static final java.lang.String _value202 = "services_glbnolocations";
    public static final java.lang.String _value203 = "services_glbservicedied";
    public static final java.lang.String _value204 = "services_glbserviceok";
    public static final java.lang.String _value205 = "slm_ALL";
    public static final java.lang.String _value206 = "slm_slmclasslimitexceeded";
    public static final java.lang.String _value207 = "slm_slmfallenbelowserious";
    public static final java.lang.String _value208 = "slm_slmfallenbelowwarn";
    public static final java.lang.String _value209 = "slm_slmnodeinfo";
    public static final java.lang.String _value210 = "slm_slmrecoveredserious";
    public static final java.lang.String _value211 = "slm_slmrecoveredwarn";
    public static final java.lang.String _value212 = "sslhw_ALL";
    public static final java.lang.String _value213 = "sslhw_sslhwfail";
    public static final java.lang.String _value214 = "sslhw_sslhwrestart";
    public static final java.lang.String _value215 = "sslhw_sslhwstart";
    public static final java.lang.String _value216 = "trafficscript_ALL";
    public static final java.lang.String _value217 = "vservers_ALL";
    public static final java.lang.String _value218 = "vservers_connerror";
    public static final java.lang.String _value219 = "vservers_connfail";
    public static final java.lang.String _value220 = "vservers_logfiledeleted";
    public static final java.lang.String _value221 = "vservers_maxclientbufferdrop";
    public static final java.lang.String _value222 = "vservers_poolpersistencemismatch";
    public static final java.lang.String _value223 = "vservers_privkeyok";
    public static final java.lang.String _value224 = "vservers_respcompfail";
    public static final java.lang.String _value225 = "vservers_responsetoolarge";
    public static final java.lang.String _value226 = "vservers_rtspstreamnoports";
    public static final java.lang.String _value227 = "vservers_sipstreamnoports";
    public static final java.lang.String _value228 = "vservers_ssldrop";
    public static final java.lang.String _value229 = "vservers_sslfail";
    public static final java.lang.String _value230 = "vservers_sslhandshakemsgsizelimit";
    public static final java.lang.String _value231 = "vservers_vscacertexpired";
    public static final java.lang.String _value232 = "vservers_vscacerttoexpire";
    public static final java.lang.String _value233 = "vservers_vscrloutofdate";
    public static final java.lang.String _value234 = "vservers_vslogwritefail";
    public static final java.lang.String _value235 = "vservers_vssslcertexpired";
    public static final java.lang.String _value236 = "vservers_vssslcerttoexpire";
    public static final java.lang.String _value237 = "vservers_vsstart";
    public static final java.lang.String _value238 = "vservers_vsstop";
    public static final java.lang.String _value239 = "zxtms_ALL";
    public static final java.lang.String _value240 = "zxtms_versionmismatch";
    public static final AlertingEventTypeEvent value1 = new AlertingEventTypeEvent(_value1);
    public static final AlertingEventTypeEvent value2 = new AlertingEventTypeEvent(_value2);
    public static final AlertingEventTypeEvent value3 = new AlertingEventTypeEvent(_value3);
    public static final AlertingEventTypeEvent value4 = new AlertingEventTypeEvent(_value4);
    public static final AlertingEventTypeEvent value5 = new AlertingEventTypeEvent(_value5);
    public static final AlertingEventTypeEvent value6 = new AlertingEventTypeEvent(_value6);
    public static final AlertingEventTypeEvent value7 = new AlertingEventTypeEvent(_value7);
    public static final AlertingEventTypeEvent value8 = new AlertingEventTypeEvent(_value8);
    public static final AlertingEventTypeEvent value9 = new AlertingEventTypeEvent(_value9);
    public static final AlertingEventTypeEvent value10 = new AlertingEventTypeEvent(_value10);
    public static final AlertingEventTypeEvent value11 = new AlertingEventTypeEvent(_value11);
    public static final AlertingEventTypeEvent value12 = new AlertingEventTypeEvent(_value12);
    public static final AlertingEventTypeEvent value13 = new AlertingEventTypeEvent(_value13);
    public static final AlertingEventTypeEvent value14 = new AlertingEventTypeEvent(_value14);
    public static final AlertingEventTypeEvent value15 = new AlertingEventTypeEvent(_value15);
    public static final AlertingEventTypeEvent value16 = new AlertingEventTypeEvent(_value16);
    public static final AlertingEventTypeEvent value17 = new AlertingEventTypeEvent(_value17);
    public static final AlertingEventTypeEvent value18 = new AlertingEventTypeEvent(_value18);
    public static final AlertingEventTypeEvent value19 = new AlertingEventTypeEvent(_value19);
    public static final AlertingEventTypeEvent value20 = new AlertingEventTypeEvent(_value20);
    public static final AlertingEventTypeEvent value21 = new AlertingEventTypeEvent(_value21);
    public static final AlertingEventTypeEvent value22 = new AlertingEventTypeEvent(_value22);
    public static final AlertingEventTypeEvent value23 = new AlertingEventTypeEvent(_value23);
    public static final AlertingEventTypeEvent value24 = new AlertingEventTypeEvent(_value24);
    public static final AlertingEventTypeEvent value25 = new AlertingEventTypeEvent(_value25);
    public static final AlertingEventTypeEvent value26 = new AlertingEventTypeEvent(_value26);
    public static final AlertingEventTypeEvent value27 = new AlertingEventTypeEvent(_value27);
    public static final AlertingEventTypeEvent value28 = new AlertingEventTypeEvent(_value28);
    public static final AlertingEventTypeEvent value29 = new AlertingEventTypeEvent(_value29);
    public static final AlertingEventTypeEvent value30 = new AlertingEventTypeEvent(_value30);
    public static final AlertingEventTypeEvent value31 = new AlertingEventTypeEvent(_value31);
    public static final AlertingEventTypeEvent value32 = new AlertingEventTypeEvent(_value32);
    public static final AlertingEventTypeEvent value33 = new AlertingEventTypeEvent(_value33);
    public static final AlertingEventTypeEvent value34 = new AlertingEventTypeEvent(_value34);
    public static final AlertingEventTypeEvent value35 = new AlertingEventTypeEvent(_value35);
    public static final AlertingEventTypeEvent value36 = new AlertingEventTypeEvent(_value36);
    public static final AlertingEventTypeEvent value37 = new AlertingEventTypeEvent(_value37);
    public static final AlertingEventTypeEvent value38 = new AlertingEventTypeEvent(_value38);
    public static final AlertingEventTypeEvent value39 = new AlertingEventTypeEvent(_value39);
    public static final AlertingEventTypeEvent value40 = new AlertingEventTypeEvent(_value40);
    public static final AlertingEventTypeEvent value41 = new AlertingEventTypeEvent(_value41);
    public static final AlertingEventTypeEvent value42 = new AlertingEventTypeEvent(_value42);
    public static final AlertingEventTypeEvent value43 = new AlertingEventTypeEvent(_value43);
    public static final AlertingEventTypeEvent value44 = new AlertingEventTypeEvent(_value44);
    public static final AlertingEventTypeEvent value45 = new AlertingEventTypeEvent(_value45);
    public static final AlertingEventTypeEvent value46 = new AlertingEventTypeEvent(_value46);
    public static final AlertingEventTypeEvent value47 = new AlertingEventTypeEvent(_value47);
    public static final AlertingEventTypeEvent value48 = new AlertingEventTypeEvent(_value48);
    public static final AlertingEventTypeEvent value49 = new AlertingEventTypeEvent(_value49);
    public static final AlertingEventTypeEvent value50 = new AlertingEventTypeEvent(_value50);
    public static final AlertingEventTypeEvent value51 = new AlertingEventTypeEvent(_value51);
    public static final AlertingEventTypeEvent value52 = new AlertingEventTypeEvent(_value52);
    public static final AlertingEventTypeEvent value53 = new AlertingEventTypeEvent(_value53);
    public static final AlertingEventTypeEvent value54 = new AlertingEventTypeEvent(_value54);
    public static final AlertingEventTypeEvent value55 = new AlertingEventTypeEvent(_value55);
    public static final AlertingEventTypeEvent value56 = new AlertingEventTypeEvent(_value56);
    public static final AlertingEventTypeEvent value57 = new AlertingEventTypeEvent(_value57);
    public static final AlertingEventTypeEvent value58 = new AlertingEventTypeEvent(_value58);
    public static final AlertingEventTypeEvent value59 = new AlertingEventTypeEvent(_value59);
    public static final AlertingEventTypeEvent value60 = new AlertingEventTypeEvent(_value60);
    public static final AlertingEventTypeEvent value61 = new AlertingEventTypeEvent(_value61);
    public static final AlertingEventTypeEvent value62 = new AlertingEventTypeEvent(_value62);
    public static final AlertingEventTypeEvent value63 = new AlertingEventTypeEvent(_value63);
    public static final AlertingEventTypeEvent value64 = new AlertingEventTypeEvent(_value64);
    public static final AlertingEventTypeEvent value65 = new AlertingEventTypeEvent(_value65);
    public static final AlertingEventTypeEvent value66 = new AlertingEventTypeEvent(_value66);
    public static final AlertingEventTypeEvent value67 = new AlertingEventTypeEvent(_value67);
    public static final AlertingEventTypeEvent value68 = new AlertingEventTypeEvent(_value68);
    public static final AlertingEventTypeEvent value69 = new AlertingEventTypeEvent(_value69);
    public static final AlertingEventTypeEvent value70 = new AlertingEventTypeEvent(_value70);
    public static final AlertingEventTypeEvent value71 = new AlertingEventTypeEvent(_value71);
    public static final AlertingEventTypeEvent value72 = new AlertingEventTypeEvent(_value72);
    public static final AlertingEventTypeEvent value73 = new AlertingEventTypeEvent(_value73);
    public static final AlertingEventTypeEvent value74 = new AlertingEventTypeEvent(_value74);
    public static final AlertingEventTypeEvent value75 = new AlertingEventTypeEvent(_value75);
    public static final AlertingEventTypeEvent value76 = new AlertingEventTypeEvent(_value76);
    public static final AlertingEventTypeEvent value77 = new AlertingEventTypeEvent(_value77);
    public static final AlertingEventTypeEvent value78 = new AlertingEventTypeEvent(_value78);
    public static final AlertingEventTypeEvent value79 = new AlertingEventTypeEvent(_value79);
    public static final AlertingEventTypeEvent value80 = new AlertingEventTypeEvent(_value80);
    public static final AlertingEventTypeEvent value81 = new AlertingEventTypeEvent(_value81);
    public static final AlertingEventTypeEvent value82 = new AlertingEventTypeEvent(_value82);
    public static final AlertingEventTypeEvent value83 = new AlertingEventTypeEvent(_value83);
    public static final AlertingEventTypeEvent value84 = new AlertingEventTypeEvent(_value84);
    public static final AlertingEventTypeEvent value85 = new AlertingEventTypeEvent(_value85);
    public static final AlertingEventTypeEvent value86 = new AlertingEventTypeEvent(_value86);
    public static final AlertingEventTypeEvent value87 = new AlertingEventTypeEvent(_value87);
    public static final AlertingEventTypeEvent value88 = new AlertingEventTypeEvent(_value88);
    public static final AlertingEventTypeEvent value89 = new AlertingEventTypeEvent(_value89);
    public static final AlertingEventTypeEvent value90 = new AlertingEventTypeEvent(_value90);
    public static final AlertingEventTypeEvent value91 = new AlertingEventTypeEvent(_value91);
    public static final AlertingEventTypeEvent value92 = new AlertingEventTypeEvent(_value92);
    public static final AlertingEventTypeEvent value93 = new AlertingEventTypeEvent(_value93);
    public static final AlertingEventTypeEvent value94 = new AlertingEventTypeEvent(_value94);
    public static final AlertingEventTypeEvent value95 = new AlertingEventTypeEvent(_value95);
    public static final AlertingEventTypeEvent value96 = new AlertingEventTypeEvent(_value96);
    public static final AlertingEventTypeEvent value97 = new AlertingEventTypeEvent(_value97);
    public static final AlertingEventTypeEvent value98 = new AlertingEventTypeEvent(_value98);
    public static final AlertingEventTypeEvent value99 = new AlertingEventTypeEvent(_value99);
    public static final AlertingEventTypeEvent value100 = new AlertingEventTypeEvent(_value100);
    public static final AlertingEventTypeEvent value101 = new AlertingEventTypeEvent(_value101);
    public static final AlertingEventTypeEvent value102 = new AlertingEventTypeEvent(_value102);
    public static final AlertingEventTypeEvent value103 = new AlertingEventTypeEvent(_value103);
    public static final AlertingEventTypeEvent value104 = new AlertingEventTypeEvent(_value104);
    public static final AlertingEventTypeEvent value105 = new AlertingEventTypeEvent(_value105);
    public static final AlertingEventTypeEvent value106 = new AlertingEventTypeEvent(_value106);
    public static final AlertingEventTypeEvent value107 = new AlertingEventTypeEvent(_value107);
    public static final AlertingEventTypeEvent value108 = new AlertingEventTypeEvent(_value108);
    public static final AlertingEventTypeEvent value109 = new AlertingEventTypeEvent(_value109);
    public static final AlertingEventTypeEvent value110 = new AlertingEventTypeEvent(_value110);
    public static final AlertingEventTypeEvent value111 = new AlertingEventTypeEvent(_value111);
    public static final AlertingEventTypeEvent value112 = new AlertingEventTypeEvent(_value112);
    public static final AlertingEventTypeEvent value113 = new AlertingEventTypeEvent(_value113);
    public static final AlertingEventTypeEvent value114 = new AlertingEventTypeEvent(_value114);
    public static final AlertingEventTypeEvent value115 = new AlertingEventTypeEvent(_value115);
    public static final AlertingEventTypeEvent value116 = new AlertingEventTypeEvent(_value116);
    public static final AlertingEventTypeEvent value117 = new AlertingEventTypeEvent(_value117);
    public static final AlertingEventTypeEvent value118 = new AlertingEventTypeEvent(_value118);
    public static final AlertingEventTypeEvent value119 = new AlertingEventTypeEvent(_value119);
    public static final AlertingEventTypeEvent value120 = new AlertingEventTypeEvent(_value120);
    public static final AlertingEventTypeEvent value121 = new AlertingEventTypeEvent(_value121);
    public static final AlertingEventTypeEvent value122 = new AlertingEventTypeEvent(_value122);
    public static final AlertingEventTypeEvent value123 = new AlertingEventTypeEvent(_value123);
    public static final AlertingEventTypeEvent value124 = new AlertingEventTypeEvent(_value124);
    public static final AlertingEventTypeEvent value125 = new AlertingEventTypeEvent(_value125);
    public static final AlertingEventTypeEvent value126 = new AlertingEventTypeEvent(_value126);
    public static final AlertingEventTypeEvent value127 = new AlertingEventTypeEvent(_value127);
    public static final AlertingEventTypeEvent value128 = new AlertingEventTypeEvent(_value128);
    public static final AlertingEventTypeEvent value129 = new AlertingEventTypeEvent(_value129);
    public static final AlertingEventTypeEvent value130 = new AlertingEventTypeEvent(_value130);
    public static final AlertingEventTypeEvent value131 = new AlertingEventTypeEvent(_value131);
    public static final AlertingEventTypeEvent value132 = new AlertingEventTypeEvent(_value132);
    public static final AlertingEventTypeEvent value133 = new AlertingEventTypeEvent(_value133);
    public static final AlertingEventTypeEvent value134 = new AlertingEventTypeEvent(_value134);
    public static final AlertingEventTypeEvent value135 = new AlertingEventTypeEvent(_value135);
    public static final AlertingEventTypeEvent value136 = new AlertingEventTypeEvent(_value136);
    public static final AlertingEventTypeEvent value137 = new AlertingEventTypeEvent(_value137);
    public static final AlertingEventTypeEvent value138 = new AlertingEventTypeEvent(_value138);
    public static final AlertingEventTypeEvent value139 = new AlertingEventTypeEvent(_value139);
    public static final AlertingEventTypeEvent value140 = new AlertingEventTypeEvent(_value140);
    public static final AlertingEventTypeEvent value141 = new AlertingEventTypeEvent(_value141);
    public static final AlertingEventTypeEvent value142 = new AlertingEventTypeEvent(_value142);
    public static final AlertingEventTypeEvent value143 = new AlertingEventTypeEvent(_value143);
    public static final AlertingEventTypeEvent value144 = new AlertingEventTypeEvent(_value144);
    public static final AlertingEventTypeEvent value145 = new AlertingEventTypeEvent(_value145);
    public static final AlertingEventTypeEvent value146 = new AlertingEventTypeEvent(_value146);
    public static final AlertingEventTypeEvent value147 = new AlertingEventTypeEvent(_value147);
    public static final AlertingEventTypeEvent value148 = new AlertingEventTypeEvent(_value148);
    public static final AlertingEventTypeEvent value149 = new AlertingEventTypeEvent(_value149);
    public static final AlertingEventTypeEvent value150 = new AlertingEventTypeEvent(_value150);
    public static final AlertingEventTypeEvent value151 = new AlertingEventTypeEvent(_value151);
    public static final AlertingEventTypeEvent value152 = new AlertingEventTypeEvent(_value152);
    public static final AlertingEventTypeEvent value153 = new AlertingEventTypeEvent(_value153);
    public static final AlertingEventTypeEvent value154 = new AlertingEventTypeEvent(_value154);
    public static final AlertingEventTypeEvent value155 = new AlertingEventTypeEvent(_value155);
    public static final AlertingEventTypeEvent value156 = new AlertingEventTypeEvent(_value156);
    public static final AlertingEventTypeEvent value157 = new AlertingEventTypeEvent(_value157);
    public static final AlertingEventTypeEvent value158 = new AlertingEventTypeEvent(_value158);
    public static final AlertingEventTypeEvent value159 = new AlertingEventTypeEvent(_value159);
    public static final AlertingEventTypeEvent value160 = new AlertingEventTypeEvent(_value160);
    public static final AlertingEventTypeEvent value161 = new AlertingEventTypeEvent(_value161);
    public static final AlertingEventTypeEvent value162 = new AlertingEventTypeEvent(_value162);
    public static final AlertingEventTypeEvent value163 = new AlertingEventTypeEvent(_value163);
    public static final AlertingEventTypeEvent value164 = new AlertingEventTypeEvent(_value164);
    public static final AlertingEventTypeEvent value165 = new AlertingEventTypeEvent(_value165);
    public static final AlertingEventTypeEvent value166 = new AlertingEventTypeEvent(_value166);
    public static final AlertingEventTypeEvent value167 = new AlertingEventTypeEvent(_value167);
    public static final AlertingEventTypeEvent value168 = new AlertingEventTypeEvent(_value168);
    public static final AlertingEventTypeEvent value169 = new AlertingEventTypeEvent(_value169);
    public static final AlertingEventTypeEvent value170 = new AlertingEventTypeEvent(_value170);
    public static final AlertingEventTypeEvent value171 = new AlertingEventTypeEvent(_value171);
    public static final AlertingEventTypeEvent value172 = new AlertingEventTypeEvent(_value172);
    public static final AlertingEventTypeEvent value173 = new AlertingEventTypeEvent(_value173);
    public static final AlertingEventTypeEvent value174 = new AlertingEventTypeEvent(_value174);
    public static final AlertingEventTypeEvent value175 = new AlertingEventTypeEvent(_value175);
    public static final AlertingEventTypeEvent value176 = new AlertingEventTypeEvent(_value176);
    public static final AlertingEventTypeEvent value177 = new AlertingEventTypeEvent(_value177);
    public static final AlertingEventTypeEvent value178 = new AlertingEventTypeEvent(_value178);
    public static final AlertingEventTypeEvent value179 = new AlertingEventTypeEvent(_value179);
    public static final AlertingEventTypeEvent value180 = new AlertingEventTypeEvent(_value180);
    public static final AlertingEventTypeEvent value181 = new AlertingEventTypeEvent(_value181);
    public static final AlertingEventTypeEvent value182 = new AlertingEventTypeEvent(_value182);
    public static final AlertingEventTypeEvent value183 = new AlertingEventTypeEvent(_value183);
    public static final AlertingEventTypeEvent value184 = new AlertingEventTypeEvent(_value184);
    public static final AlertingEventTypeEvent value185 = new AlertingEventTypeEvent(_value185);
    public static final AlertingEventTypeEvent value186 = new AlertingEventTypeEvent(_value186);
    public static final AlertingEventTypeEvent value187 = new AlertingEventTypeEvent(_value187);
    public static final AlertingEventTypeEvent value188 = new AlertingEventTypeEvent(_value188);
    public static final AlertingEventTypeEvent value189 = new AlertingEventTypeEvent(_value189);
    public static final AlertingEventTypeEvent value190 = new AlertingEventTypeEvent(_value190);
    public static final AlertingEventTypeEvent value191 = new AlertingEventTypeEvent(_value191);
    public static final AlertingEventTypeEvent value192 = new AlertingEventTypeEvent(_value192);
    public static final AlertingEventTypeEvent value193 = new AlertingEventTypeEvent(_value193);
    public static final AlertingEventTypeEvent value194 = new AlertingEventTypeEvent(_value194);
    public static final AlertingEventTypeEvent value195 = new AlertingEventTypeEvent(_value195);
    public static final AlertingEventTypeEvent value196 = new AlertingEventTypeEvent(_value196);
    public static final AlertingEventTypeEvent value197 = new AlertingEventTypeEvent(_value197);
    public static final AlertingEventTypeEvent value198 = new AlertingEventTypeEvent(_value198);
    public static final AlertingEventTypeEvent value199 = new AlertingEventTypeEvent(_value199);
    public static final AlertingEventTypeEvent value200 = new AlertingEventTypeEvent(_value200);
    public static final AlertingEventTypeEvent value201 = new AlertingEventTypeEvent(_value201);
    public static final AlertingEventTypeEvent value202 = new AlertingEventTypeEvent(_value202);
    public static final AlertingEventTypeEvent value203 = new AlertingEventTypeEvent(_value203);
    public static final AlertingEventTypeEvent value204 = new AlertingEventTypeEvent(_value204);
    public static final AlertingEventTypeEvent value205 = new AlertingEventTypeEvent(_value205);
    public static final AlertingEventTypeEvent value206 = new AlertingEventTypeEvent(_value206);
    public static final AlertingEventTypeEvent value207 = new AlertingEventTypeEvent(_value207);
    public static final AlertingEventTypeEvent value208 = new AlertingEventTypeEvent(_value208);
    public static final AlertingEventTypeEvent value209 = new AlertingEventTypeEvent(_value209);
    public static final AlertingEventTypeEvent value210 = new AlertingEventTypeEvent(_value210);
    public static final AlertingEventTypeEvent value211 = new AlertingEventTypeEvent(_value211);
    public static final AlertingEventTypeEvent value212 = new AlertingEventTypeEvent(_value212);
    public static final AlertingEventTypeEvent value213 = new AlertingEventTypeEvent(_value213);
    public static final AlertingEventTypeEvent value214 = new AlertingEventTypeEvent(_value214);
    public static final AlertingEventTypeEvent value215 = new AlertingEventTypeEvent(_value215);
    public static final AlertingEventTypeEvent value216 = new AlertingEventTypeEvent(_value216);
    public static final AlertingEventTypeEvent value217 = new AlertingEventTypeEvent(_value217);
    public static final AlertingEventTypeEvent value218 = new AlertingEventTypeEvent(_value218);
    public static final AlertingEventTypeEvent value219 = new AlertingEventTypeEvent(_value219);
    public static final AlertingEventTypeEvent value220 = new AlertingEventTypeEvent(_value220);
    public static final AlertingEventTypeEvent value221 = new AlertingEventTypeEvent(_value221);
    public static final AlertingEventTypeEvent value222 = new AlertingEventTypeEvent(_value222);
    public static final AlertingEventTypeEvent value223 = new AlertingEventTypeEvent(_value223);
    public static final AlertingEventTypeEvent value224 = new AlertingEventTypeEvent(_value224);
    public static final AlertingEventTypeEvent value225 = new AlertingEventTypeEvent(_value225);
    public static final AlertingEventTypeEvent value226 = new AlertingEventTypeEvent(_value226);
    public static final AlertingEventTypeEvent value227 = new AlertingEventTypeEvent(_value227);
    public static final AlertingEventTypeEvent value228 = new AlertingEventTypeEvent(_value228);
    public static final AlertingEventTypeEvent value229 = new AlertingEventTypeEvent(_value229);
    public static final AlertingEventTypeEvent value230 = new AlertingEventTypeEvent(_value230);
    public static final AlertingEventTypeEvent value231 = new AlertingEventTypeEvent(_value231);
    public static final AlertingEventTypeEvent value232 = new AlertingEventTypeEvent(_value232);
    public static final AlertingEventTypeEvent value233 = new AlertingEventTypeEvent(_value233);
    public static final AlertingEventTypeEvent value234 = new AlertingEventTypeEvent(_value234);
    public static final AlertingEventTypeEvent value235 = new AlertingEventTypeEvent(_value235);
    public static final AlertingEventTypeEvent value236 = new AlertingEventTypeEvent(_value236);
    public static final AlertingEventTypeEvent value237 = new AlertingEventTypeEvent(_value237);
    public static final AlertingEventTypeEvent value238 = new AlertingEventTypeEvent(_value238);
    public static final AlertingEventTypeEvent value239 = new AlertingEventTypeEvent(_value239);
    public static final AlertingEventTypeEvent value240 = new AlertingEventTypeEvent(_value240);
    public java.lang.String getValue() { return _value_;}
    public static AlertingEventTypeEvent fromValue(java.lang.String value)
          throws java.lang.IllegalArgumentException {
        AlertingEventTypeEvent enumeration = (AlertingEventTypeEvent)
            _table_.get(value);
        if (enumeration==null) throw new java.lang.IllegalArgumentException();
        return enumeration;
    }
    public static AlertingEventTypeEvent fromString(java.lang.String value)
          throws java.lang.IllegalArgumentException {
        return fromValue(value);
    }
    public boolean equals(java.lang.Object obj) {return (obj == this);}
    public int hashCode() { return toString().hashCode();}
    public java.lang.String toString() { return _value_;}
    public java.lang.Object readResolve() throws java.io.ObjectStreamException { return fromValue(_value_);}
    public static org.apache.axis.encoding.Serializer getSerializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new org.apache.axis.encoding.ser.EnumSerializer(
            _javaType, _xmlType);
    }
    public static org.apache.axis.encoding.Deserializer getDeserializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new org.apache.axis.encoding.ser.EnumDeserializer(
            _javaType, _xmlType);
    }
    // Type metadata
    private static org.apache.axis.description.TypeDesc typeDesc =
        new org.apache.axis.description.TypeDesc(AlertingEventTypeEvent.class);

    static {
        typeDesc.setXmlType(new javax.xml.namespace.QName("http://soap.zeus.com/zxtm/1.0/", "Alerting.EventType.Event"));
    }
    /**
     * Return type metadata object
     */
    public static org.apache.axis.description.TypeDesc getTypeDesc() {
        return typeDesc;
    }

}
